name: Publish Docker image
on:
  release:
    types: [published]
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: paprikapulver/node-test/node-test
          tag_with_ref: true
      - name: CapRover Image Deploy
        uses: stardustventures/caprover-deploy@v2
        with:
          server: 'https://captain.cloud.paprikasoft.de'
          password: '${{ secrets.CAPROVER_PASSWORD }}'
          appname: 'note-test'
          image: docker.pkg.github.com/paprikapulver/node-test/node-test         
